export { default as Logo } from '@/components/logo'
export { default as Icon } from '@/components/icon'
export { default as Banner } from '@/components/banner'
export { default as RentalCard } from '@/components/rental-card'
export { default as Gallery } from '@/components/gallery'
export { default as Accordion } from '@/components/accordion'
